{"version":3,"sources":["app.js"],"names":["doException","Error","noException","callException","type"],"mappings":"AAAA,SAASA,WAAT,GAAuB;AACrB,QAAM,IAAIC,KAAJ,CAAU,SAAV,CAAN;AACD;;AAED,SAASC,WAAT,GAAuB;AACrB,SAAO,IAAP;AACD;;AAED,SAASC,aAAT,CAAuBC,IAAvB,EAA6B;AAC3B,MAAIA,IAAI,KAAK,IAAb,EAAmB;AACjBJ,IAAAA,WAAW;AACZ,GAFD,MAEO;AACLE,IAAAA,WAAW;AACZ;AACF,EAED;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;;;AAEAF,WAAW","file":"app.c328ef1a.js","sourceRoot":"..","sourcesContent":["function doException() {\n  throw new Error(\"와! 오류야!\");\n}\n\nfunction noException() {\n  return true;\n}\n\nfunction callException(type) {\n  if (type === \"do\") {\n    doException();\n  } else {\n    noException();\n  }\n}\n\n// function main() {\n//   try {\n//     callException(\"do\");\n//   } catch (e) {\n//     console.log(e);\n//   } finally {\n//     // 예외가 일어나든 안일어나든 반드시 실행되어야 할 코드가 작성되어야함\n//     console.log(\"done\");\n//   }\n// }\n\ndoException();\n"]}